spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/batch__2023_06_06
    username: testuser
    password: 5678